version: '2'

services:
  nginx:
    image: nginx:1.14.1
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80

  php-fpm:
    image: php:7.1.24-fpm
    volumes:
      - .:/var/www/html
