global:
  scrape_interval: 5s
  external_labels:
      monitor: 'my-monitor'
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
        - targets: ['localhost:9090']
  - job_name: 'node resources'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'node-exporter:9100'
