version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 9995:80
    networks:
      - mysql_default
    volumes:
      - /sessions

networks:
  mysql_default:
    external: true

# 使用
# HOST: mysql8:3306 或者 mysql58:3306
# 认证: root/112233      root/112233
