version: '2'

services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - 127.0.0.1:9994:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

# with nginx proxy manager(npm), delete it when you do not use nginx proxy manager
networks:
  default:
    external:
      name: npm
