version: "2"

services:
  zentao-mysql:
    image: bitnami/mysql:8.0
    container_name: zentao-mysql
    ports:
      - "21306:3306"
    volumes:
      - ./data/db:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Zentao123
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6

  # zentao service
  zentao:
    image: easysoft/zentao:18.8
    container_name: zentao
    ports:
      - "21888:80"
    volumes:
      - ./data/file:/data
    depends_on:
      - zentao-mysql
    environment:
      - ZT_MYSQL_HOST=zentao-mysql
      - ZT_MYSQL_PORT=3306
      - ZT_MYSQL_USER=root
      - ZT_MYSQL_PASSWORD=pass4Zentao123
      - ZT_MYSQL_DB=zentao
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - LDAP_ENABLED=false
      - SMTP_ENABLED=false
      - APP_DEFAULT_PORT=80
      - APP_DOMAIN=chandao.dev.muke.design
      - PROTOCOL_TYPE=http
      - IS_CONTAINER=true
      - LINK_GIT=false
      - LINK_CI=false
    networks:
      - zentao-net

networks:
  zentao-net:
    driver: bridge
